baseURL = 'https://100trillion.github.io/'
languageCode = 'ko-kr'
title = 'greenerseoul'
theme = ['ananke']

SectionPagesMenu = "main"
Paginate = 9
enableRobotsTXT = true

[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[params]
text_color = ""
author = ""
favicon = ""
site_logo = ""
description = ""
# choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
background_color_class = "bg-dark-green"
recent_posts_number = 3

[[params.ananke_socials]]
name = "facebook"
url = "https://www.facebook.com/profile.php?id=100003064410702"